Introduce parents
kiegroup/run-tests-with-build pull request #25
Opened 2021-05-10 14:39 UTC by jstastny-cz

Refactor of the repo structure.

Main themes:
* extracting sources download to separate modules that can be ad-hoc brought into Maven reactor to provide sources needed for testing
* introducing grouping parent for repositories
* the parent modules are the invocation points for tests for given repository (e.g. kogito-runtimes)
  * defining profiles to group child module with the source-downloading module (mentioned above)

2021-05-11 06:55 UTC, dupliaka approved these changes

2021-05-11 07:05 UTC, jomarko reviewed
Jan, this is amazing piece of work! Thank you.

2021-05-11 07:06 UTC, jomarko commented on pom.xml
> +      ${main.basedir}/run-tests-with-build-sources-download/target/sources
I understand already, it is a dependency in some leaves, just not too common for my experience from projects I worked on.

2021-05-11 07:23 UTC, hellowdan approved these changes
Thanks for this!!!

2021-05-11 07:42 UTC, jstastny-cz commented on run-tests-with-build-optaplanner-parent/optaplanner-project-sources-test/pom.xml
> +          <parallelThreads>1</parallelThreads>
Yeah, result of copy&paste probably.

2021-05-11 11:54 UTC, jomarko approved these changes
thank you

2021-05-11 12:44 UTC, radtriste requested changes
instead of `optaplanner.download.build.version` and `kogito.download.build.version`, would it make sense to have only one `download.build.version` ?
or we want to keep it safe ?

2021-05-11 12:44 UTC, radtriste commented on run-tests-with-build-optawebs-parent/README.md
> +  -Doptawebs.test=project-sources \
```suggestion
  -Dtest.type=project-sources \
```

2021-05-11 12:44 UTC, radtriste commented on run-tests-with-build-optawebs-parent/README.md
> +  -Doptawebs.test=project-sources \
```suggestion
  -Dtest.type=project-sources \
```

2021-05-17 08:15 UTC, radtriste approved these changes

2021-05-17 08:20 UTC, merged